customer.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/postgres/s1/customer.tbl
lineorder.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/postgres/s1/lineorder.tbl
part.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/postgres/s1/part.tbl
supplier.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/postgres/s1/supplier.tbl
date.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/postgres/s1/date.tbl
