customer.data=src/main/resources/customer.tbl
lineorder.data=src/main/resources/lineorder.tbl
part.data=src/main/resources/part.tbl
supplier.data=src/main/resources/supplier.tbl
date.data=src/main/resources/date.tbl

#customer.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/medium-sample-postgres/customer.tbl
#lineorder.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/medium-sample-postgres/lineorder.tbl
#part.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/medium-sample-postgres/part.tbl
#supplier.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/medium-sample-postgres/supplier.tbl
#date.data=/home/zeyuanhu/projects/eyalroz-ssb-dbgen/medium-sample-postgres/date.tbl
