# JOB
db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/main.duckdb
# Exp2.5
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/exp25.duckdb
# Exp2.8
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/exp28.duckdb
# Exp2.9
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/exp29.duckdb
# Exp2.9O
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/exp29O.duckdb
# SSB S1
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/treeTracker/ssb-s1.duckdb
# SSB S2
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/treeTracker/ssb-s2.duckdb
# SSB S3
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/treeTracker/ssb-s3.duckdb
# SSB S10
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/treeTracker/ssb-s10.duckdb
# TPC-H S1
#db.url=jdbc:duckdb:/home/zeyuanhu/projects/treetracker2/treeTracker/tpch-s1.duckdb
db.user=postgres
db.password=password
