#db.url=jdbc:sqlite:/home/zeyuanhu/projects/treetracker2/imdb.sqlitedb
#db.url=jdbc:sqlite:/home/zeyuanhu/projects/treetracker2/tpch.sqlitedb
db.url=jdbc:sqlite:/home/zeyuanhu/projects/treetracker2/ssb.sqlitedb
